### ISSUE TITLE
Power the bord from battery without pressing reset

### ISSUE THREAD

**Issue by xXBitMinisterenXx** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#100]
Hello is there a way to power the bord from a battery without pressing reset?

**Comment by lewisxhe** [comment]
If you use the IP5306 version, then you must press the reset button to start power supply, other versions do not need

**Comment by mashrurbd** [comment]
Hello, I discovered that Whenever I plug in a 18650 battery, after presssing the reset button, it works. 

But whenever I try to add a 5V DC charger to the battery jacks, it wont start after pressing the reset bitton. Can you please help? 

Thanks in advance.
