### ISSUE TITLE
Putting ESP32 to sleep and keep SIM800 active

### ISSUE THREAD

**Issue by golden-oldie** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#102]
Is there anyway to put the ESP32 into deep sleep but keep the SIM800 active to be able to wake the ESP32? So far everytime I put the ESP into deep sleep the modem will also go to sleep and I cannot setup the power pin of the modem to stay active as it's not a GPIO pin. The only thin that's worked so far its light_sleep but it's not saving as much power as I would like for my low power project.

**Comment by lewisxhe** [comment]
I submitted an example, you only need to use gpio_hold_en(GPIO_NUM_25);  you can keep the Modem open, and esp32 can be set to sleep

https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/blob/6a2f1d6b9959cbeadd42a5d28546dea99fde10c3/examples/Arduino_KeepActive/Arduino_KeepActive.ino#L98
