### ISSUE TITLE
T-Call SIM800C MODEM RX+TX pin definition mismatch in doc/examples

### ISSUE THREAD

**Issue by toph84** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#106]
Hi,

I've noticed a mismatch in pin definitions for the SIM800C-variant of LilyGo T-Call.

In [documentation](https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/blob/master/doc/SIM800C_AXP192.MD#pin-definition) it is:
MODEM TX | 26
MODEM RX | 27

In [utilities.h](https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/blob/1eca2b2b40c641e0103e63bb03a4d5261a0beb0a/examples/Arduino_TinyGSM/utilities.h#L60) it is:
MODEM_TX             27
MODEM_RX             26

I guess the examples are right, right?

Best wishes
Chris

**Comment by lewisxhe** [comment]
The example is correct, maybe the document is wrong. I will correct it.
