### ISSUE TITLE
Is it possible to disable pin 32 DTR function?

### ISSUE THREAD

**Issue by ykolerov** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#110]
Hi, I dont need modem DTR associated with pin 32. Is it possible to disable this function in code or maybe by desoldering something from the board?

**Comment by lewisxhe** [comment]
DTR is only used as the IO port for the modem to wake up from sleep, you don't need to use it.

**Comment by ykolerov** [comment]
I need to use pin 32 as gpio. When I use it as gpio, modem goes to sleep when I have high level on it. I dont need this functionality. Any way to get rid of it?

**Comment by lewisxhe** [comment]
If you want to use GPIO32 and DTR wakeup is not applicable, then you can remove the series resistor. Which board are you using?

**Comment by ykolerov** [comment]
I have v1.3 and I also have ordered v1.4. need to disable DTR on both.
Any chance to disable "spectial functions" on other pins (0/4/5/12/33)?

**Comment by lewisxhe** [comment]
V1.3 is not connected to DTR, you can use GPIO32 directly. V1.4 you need to remove the resistor to use GPIO32

**Comment by ykolerov** [comment]
Thanks for clarification. Which exactly resistor should I remove?

**Comment by lewisxhe** [comment]
@ykolerov
 I will reply to you after asking the hardware engineer tomorrow.

**Comment by ykolerov** [comment]
Thank you! Please also ask him/her about other pins :-)

**Comment by lewisxhe** [comment]
My network is not good, I cannot upload pictures, please leave your email, I will send it to you by email

**Comment by ykolerov** [comment]
I sent you an email to your address that is indicated in your github profile. Thanks!
