### ISSUE TITLE
Any chance for an example with MQTT and TLS/SSL?

### ISSUE THREAD

**Issue by kedzior-io** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#116]
It would be great if you guys could provide an example for MQTT with TLS/SSL configuration? 
Most of the IOT cloud providers require it today.

Here is an example of MQTT I'm talking about: 
https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/blob/master/examples/Arduino_MQTT/Arduino_MQTT.ino

Here specifically talking about connecting it to Azure IOT Hub:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#using-the-mqtt-protocol-directly-as-a-device

and required TLS/SSL configuration:
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#tlsssl-configuration

Thanks!

**Comment by lewisxhe** [comment]
Currently, the built-in firmware of 800L does not support SSL and MQTT. I will look for SIMCom to provide technical support and ask them to provide me with a new version of the firmware. I will add it to the example when I finish the test.

**Comment by kedzior-io** [comment]
> Currently, the built-in firmware of 800L does not support SSL and MQTT. I will look for SIMCom to provide technical support and ask them to provide me with a new version of the firmware. I will add it to the example when I finish the test.

Awesome! Thank you!

**Comment by lewisxhe** [comment]
I am in China and I cannot access azure. I will try to connect to another IOT platform for testing. Do you have a recommended IOT platform? 

@kedzior-io

**Comment by lewisxhe** [comment]
I did not find the English document of 800L SSL, you can view the Chinese one. Hope it helps you
https://cn.simcom.com/product/SIM800L.html
