### ISSUE TITLE
TCall SIM800 Cannot connect to Arduino IDE

### ISSUE THREAD

**Issue by eduardcabanas** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#136]
Hi,

I followed the instructions and I added the board manager all ESP32 devices. I connect to USB-c and I tried to connect multiple boards, but noone appears on my serial. I switched the 0 port with gnd but no board detect. Do you have any guide or way to connect the board?

Thanks in advance

Esuard

**Comment by crbble** [comment]
Hi, have you been able to solve your issue?
