### ISSUE TITLE
Unable to use the 3 HardwareSerial ports concurrently.

### ISSUE THREAD

**Issue by emerout** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#159]
Hello, 

I'm unable to use the 3 HardwareSerial ports concurrently.

- `Serial` for console monitor on USB
- `Serial1` for onboard SIM800L modem 
- `Serial2` for a Slave Modbus/RS-485 external module (pins 14 and 27) 

The Modbus receive data, but does not respond to Master.

Modbus is ok if I doesn't start GSM.

See https://github.com/espressif/arduino-esp32/issues/1314#issuecomment-664794343 for a similar issue.

**Comment by LilyGO** [comment]
Three serial ports are normal.
Serial2 . You can't use pin 27.  27 is the TX pin of Sim800
