### ISSUE TITLE
SD Card and Modem

### ISSUE THREAD

**Issue by heisenbergv6** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#160]
Hi! When try use sd card and Tinygsm i cant init my modem. i put all sentences as the example published in order but i cant init it. if i comment setupSDCard() the modem init correct. Where i have the problem?

void setup()
{
    // Set console baud rate
    SerialMon.begin(115200);

    SerialMon.println("Starting");

    delay(10);

    setupSDCard();
    setupModem();
    SerialAT.begin(115200, SERIAL_8N1, MODEM_RX, MODEM_TX);
    
    modem.restart();
}

thanks you in advance!
Greetings

**Comment by LilyGO** [comment]
> Hi! When try use sd card and Tinygsm i cant init my modem. i put all sentences as the example published in order but i cant init it. if i comment setupSDCard() the modem init correct. Where i have the problem?
> 
> void setup()
> {
> // Set console baud rate
> SerialMon.begin(115200);
> 
> ```
> SerialMon.println("Starting");
> 
> delay(10);
> 
> setupSDCard();
> setupModem();
> SerialAT.begin(115200, SERIAL_8N1, MODEM_RX, MODEM_TX);
> 
> modem.restart();
> ```
> 
> }
> 
> thanks you in advance!
> Greetings

Hello, SIM800 series does not support SD cards.
