### ISSUE TITLE
Cannot compile: utilities.h: No such file or directory

### ISSUE THREAD

**Issue by jbrepogmailcom** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#161]
Getting this error

**Comment by mashrurbd** [comment]
Make a file utilities.h and paste the contents from [https://raw.githubusercontent.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/master/examples/Arduino_SMS/utilities.h](utilities.h)
