### ISSUE TITLE
Guide me to use 128x64 Monochrome LCD with u8g2 lib.

### ISSUE THREAD

**Issue by mashrurbd** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#162]
First of all, thanks for the library! I have been using TTGO T-Call for less than a month now and I am fond of its features!

I am using a 128x64 Monochrome LCD with u8g2 library.  The problem is that the display does not work all the time.

In their demo code, they mentioned a constructor:
```cpp
// Please note that I changed the SPI, Correct me if I am wrong.
#define LCD_CS 33
#define LCD_SCLK 14 //25
#define LCD_MISO 12 //27
#define LCD_MOSI 13 //26

// SPIClass SPI1(HSPI);

U8G2_ST7920_128X64_F_SW_SPI u8g2(U8G2_R0, /* clock=*/ LCD_SCLK, /* data=*/ LCD_MOSI, /* CS=*/ LCD_CS, /* reset=*/ 22);
```

In the last line, i.e.:
```cpp
U8G2_ST7920_128X64_F_SW_SPI u8g2(U8G2_R0, /* clock=*/ LCD_SCLK, /* data=*/ LCD_MOSI, /* CS=*/ LCD_CS, /* reset=*/ 22);
```
the reset pin is set to GPIO: 22, can you suggest me another pin for this constructor? 

Also, I need to change these pins: 
```cpp
#define LCD_SCLK 14 //25
#define LCD_MISO 12 //27
#define LCD_MOSI 13 //26
```
**Please reply with a correct constructor and pins, Thanks in advance!**

**Comment by LilyGO** [comment]
You first need to know which model your OLED screen driver chip is.

**Comment by mashrurbd** [comment]
I am using 128x64 LCD Monochrome display, not the OLED display. 
Please have a look at the photo:
![image](https://user-images.githubusercontent.com/12530291/132939925-bb7a52c8-6960-41aa-8486-1b8dd203e95d.png)

**Comment by mashrurbd** [comment]
Please note that the controller model is: ST7920
