### ISSUE TITLE
Pushbutton on T-Call-SIM800C (with AXP192)

### ISSUE THREAD

**Issue by ClemensGruber** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#163]
What is the pushbutton on the C model next the SIM800C for, see picture? And how it is connected to the board. Can I use it as "common" push button, is it connected to an ESP pin? 

On https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/ I found 

> If you use the AXP192 power management chip, you need to press and hold the PWR button for 2 seconds to turn on the power supply. By default, the AXP192 will be powered on when the battery is inserted.

Do I have to switch on a feature for that? With a sketch based on the [TinyGSM example](https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/tree/master/examples/Arduino_TinyGSM) I can push the button short or 2 sec or longer with no effect. So it seems that I have to activate it somewhere -- or, in case I do not use the feature, I can use the button for my purpurse in case it is connected to the ESP?

![2021-09-11 11_52_20-Product jpg (JPEG-Grafik, 1068 × 1068 Pixel) - SeaMonkey](https://user-images.githubusercontent.com/36139413/132944433-6681144f-976e-46ac-bea8-88c66a9a2fa5.png)

**Comment by LilyGO** [comment]
> What is the pushbutton on the C model next the SIM800C for, see picture? And how it is connected to the board. Can I use it as "common" push button, is it connected to an ESP pin?
> 
> On https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/ I found
> 
> > If you use the AXP192 power management chip, you need to press and hold the PWR button for 2 seconds to turn on the power supply. By default, the AXP192 will be powered on when the battery is inserted.
> 
> Do I have to switch on a feature for that? With a sketch based on the [TinyGSM example](https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/tree/master/examples/Arduino_TinyGSM) I can push the button short or 2 sec or longer with no effect. So it seems that I have to activate it somewhere -- or, in case I do not use the feature, I can use the button for my purpurse in case it is connected to the ESP?
> 
> ![2021-09-11 11_52_20-Product jpg (JPEG-Grafik, 1068 × 1068 Pixel) - SeaMonkey](https://user-images.githubusercontent.com/36139413/132944433-6681144f-976e-46ac-bea8-88c66a9a2fa5.png)



> What is the pushbutton on the C model next the SIM800C for, see picture? And how it is connected to the board. Can I use it as "common" push button, is it connected to an ESP pin?
> 
> On https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/ I found
> 
> > If you use the AXP192 power management chip, you need to press and hold the PWR button for 2 seconds to turn on the power supply. By default, the AXP192 will be powered on when the battery is inserted.
> 
> Do I have to switch on a feature for that? With a sketch based on the [TinyGSM example](https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/tree/master/examples/Arduino_TinyGSM) I can push the button short or 2 sec or longer with no effect. So it seems that I have to activate it somewhere -- or, in case I do not use the feature, I can use the button for my purpurse in case it is connected to the ESP?
> 
> ![2021-09-11 11_52_20-Product jpg (JPEG-Grafik, 1068 × 1068 Pixel) - SeaMonkey](https://user-images.githubusercontent.com/36139413/132944433-6681144f-976e-46ac-bea8-88c66a9a2fa5.png)

Hello, this button is not connected to ESP32.

**Comment by capedra** [comment]
@LilyGO sometimes the board does not power on when I plug in the battery or press the EN button, forcing me to press the PWR button for 2 seconds to power up. I don't know how I may solve it since the PWR button goes to one of the PMU pins.
