### ISSUE TITLE
Powering t-call v1.3 with 5 volts

### ISSUE THREAD

**Issue by thassler** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#168]
Hello,

I want to power the t-call v1.3 with 5v but don't want to use a usb cable. The pinout says that the 5v pin is 5v-OUT. Is it possible to power the board through the 5v-OUT pin or it is just an 5v output? It is not clear if it can be used to power the board. Other boards have the pin labeled as 5v-IN.

Thanks in advance.

**Comment by pperzyna** [comment]
@LilyGO If I provide 5V on this pin on a device with AXP192. Do I still have to press the button or will it auto power on?

**Comment by LilyGO** [comment]
Automatically turn on
