### ISSUE TITLE
SPI SD card module and SIM800L module together don'T work.

### ISSUE THREAD

**Issue by marmou-fritzing** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#171]
Good afternoon.
I have an problem with simultaneously function of SIM800L and SPI SD module together.
Because standard SPI pins (18,19,23,5) and pins for SIM800L controls (26,27,4,5,23) are shared (23 and 5), then I try redirect SPI to different pins.
I use SPI.begin(18,19,0,2); and on these pins I have connected SD. module.
When i have commented SD.begin(); then SIM800L works perfectly. Starting sequention is without problems.
When i uncomment SD.begin(); then I got from SIM800 an text "1: 5004 0000;0: 102C 0001;1: 1005 0000;0: 0000 0001 [0000];0: 0000 00A3;ystem halt!". SD card works perfectly.
When i comment SD.begin(); then SIM800L works again without problems.
Have You any experiences about this issue ?
Thank You.

**Comment by marmou-fritzing** [comment]
Already solved - reconnected to another pins: 18,19,14,25. All works.

**Comment by afriansy4h** [comment]
@marmou-fritzing  you are my Superstart !
Thanks
