### ISSUE TITLE
+ and - on the Board

### ISSUE THREAD

**Issue by gorogdaniel** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#172]
For what is the + and - on the board i dont find any thing in the documentation.

Thank you very much

**Comment by LilyGO** [comment]
Can you send pictures to point out the place?I think it's a microphone or a speaker.

**Comment by gorogdaniel** [comment]
![Screenshot_2021-11-04-04-46-01-719_com mi globalbrowser](https://user-images.githubusercontent.com/44518652/140254856-ec3b66c3-73d9-4389-84c0-a0036e8ab4be.jpg)

Hi, thanks for the answer. I mean the +and - in the middle of the board

**Comment by LilyGO** [comment]
This is the vibration motor
