### ISSUE TITLE
Board CP2104

### ISSUE THREAD

**Issue by idkq** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#174]
Can you please upload the schematics and details for CP2104? It seems different from all other boards in the pictures. Which #define should be used?

**Comment by LilyGO** [comment]
Hello, can you send me a picture?

**Comment by idkq** [comment]
![IMG_4144](https://user-images.githubusercontent.com/76702881/140066211-7d353614-dd8a-4e97-a7d8-5ba5b4d3e29a.jpg)
![IMG_4143](https://user-images.githubusercontent.com/76702881/140066213-d384c387-79c6-46ad-b242-5b13fe96138c.jpg)

**Comment by LilyGO** [comment]
#define SIM800L_IP5306_VERSION_20200811

**Comment by idkq** [comment]
Do we have the schematics?

**Comment by LilyGO** [comment]
[schematic](https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/tree/master/schematic)
