### ISSUE TITLE
Can I power LilyGo T-Call via +ve/-ve solder points?

### ISSUE THREAD

**Issue by openboxtt** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#204]
My project has bare wire 5v supply wires. Rather than solder on USB c connectors can i utilize the fairly prominently labeled + and - ports I see on the middle of the board between pins 14 and NC?

I can't find mine voltmeter stm to even investigate these solder points.

Thanks!
![16505764040586788952730917249570](https://user-images.githubusercontent.com/39965097/164555049-ad340a16-66bf-4994-927e-af374cff8ab1.jpg)

**Comment by LilyGO** [comment]
Just the motor
