### ISSUE TITLE
Where to buy?

### ISSUE THREAD

**Issue by pixelfriese** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#211]
On Aliexpress, the LilyGo store no longer shows any items when I go to all products. 

![grafik](https://user-images.githubusercontent.com/13178131/177007563-127601a2-08f4-46ff-9ffe-fba7076e7fc2.png)

**Comment by LilyGO** [comment]
Hello.
under repair. You can also buy them [here ](https://www.tindie.com/products/lilygo/lilygo-ttgo-t-call-v14)
