### ISSUE TITLE
Need help: I connected the battery to the esp32 and it does not work properly.

### ISSUE THREAD

**Issue by xBLACKICEx** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#216]
Need help: I connected the battery to the esp32 and it does not work properly.

Questions

* battery work must first be connected to usb c to
* Unplug the usb c can only work for 30 seconds~1min

[battry is EEMB 3.7 2000mAh(7.4Wh)](https://jp.eemb.com/public/Download/Rechargeable-Lithium-Battery/Li-Polymer-Battery/Standard-Version/LP103454.pdf)

Battery voltage is 4.09V when tested with a multimeter

Battery directly connected to esp32 outflow voltage is 2.25V~2.30V

Connect to usb c and pull out quickly, the battery can keep the voltage at 4.09v for a short time（30~60s）

Continuously connected to usb, the measured voltage is 4.15V

**The code I used to test** See if the led can light up
```c++
void setup() {
  pinMode(12, OUTPUT);
  digitalWrite(12, HIGH);
}

void loop() {
}
```

**I measured the voltage here on the board:**
![esp32 sim800l test volt](https://user-images.githubusercontent.com/51036094/184537292-b09529e9-4f45-4778-b581-fb882d4e9d97.jpg)

**Comment by LilyGO** [comment]
Hello，Can you tell me the version? silkscreen on board

**Comment by xBLACKICEx** [comment]
> Hello，Can you tell me the version? silkscreen on board

Sorry I couldn't find the version on the board, so I took two photos

![20220815_090823](https://user-images.githubusercontent.com/51036094/184591627-1efc009d-32c9-45ea-877b-e118a7859770.jpg)
![20220815_090654](https://user-images.githubusercontent.com/51036094/184591637-dc201489-cec6-471d-bb60-aa2317b1894f.jpg)

**Comment by LilyGO** [comment]
Can you run this [example ](https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/tree/master/examples/Arduino_TinyGSM) normally?

**Comment by xBLACKICEx** [comment]
> Can you run this [example ](https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/tree/master/examples/Arduino_TinyGSM) normally?

i think yes is print out 
![图片](https://user-images.githubusercontent.com/51036094/184642620-b94c8cc2-e95f-448c-99e2-f5e874008d48.png)
in serial

**Comment by LilyGO** [comment]
Can run the example normally
