### ISSUE TITLE
LilyGo-TTGO-800L Blynk v1.4 - Default Program

### ISSUE THREAD

**Issue by emiroglu** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#224]
I recently got the board. I haven't flashed anything on it yet but when I plug it in, it starts flashing two LED's in an asynchronized way. What is the default software setup that comes with these boards? What is installed? What does it do?

Here are the photos of the board as reference.

![unnamed](https://user-images.githubusercontent.com/49313755/206801956-b9b2589d-1fd8-4b0c-a164-412979bd6fca.jpg)
![IMG-3214](https://user-images.githubusercontent.com/49313755/206801978-c20ef710-88aa-464b-bf50-8460d942f097.jpg)

**Comment by lewisxhe** [comment]
By default, the test program written by arduino runs ATdebug
