### ISSUE TITLE
UART

### ISSUE THREAD

**Issue by IVANSAMOA** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#225]
In addition to GSM communication on pins 26 and 27, I want to use a UART to listen another bus.
I am looking for the pins on the ESP32 module and the Lilygo board.
On ESP32 it seems to have a UART2 on pins 16 and 17, but which Lilygo pins do I have to use for listening the UART?

I have tested 10 and 11 but it doesn't work.

Thanks

**Comment by lewisxhe** [comment]
Like this : 
```
 Serial2.begin(115200, SERIAL_8N1, rxPin, txPin);

```

**Comment by IVANSAMOA** [comment]
Ok, but what pin is rxPin? and txPin?

**Comment by mide-X** [comment]
Hello @IVANSAMOA , What pins did you use for rxPin and txPin
