### ISSUE TITLE
problem to identify board and PINOUT connection

### ISSUE THREAD

**Issue by pilot1981** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#228]
Hi,
I buyed new board in attachment. I don't understand which version is this.

![28520303-C593-4B30-BCCC-DEB928756685](https://user-images.githubusercontent.com/46350465/219319796-7a52e0fb-770a-4aae-aa6f-3c4d020dc8b8.jpg)

you can help me to understand version of boar and which pin are connected between ESP32 and SIM800L module? I have to configure them in ESPHOME firmware.

regards

**Comment by lewisxhe** [comment]
This is the version of IP5306 power management. Pinout, look here

https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/blob/ef7ae1440150f5bc5a41f74bfd14447ea1c416c5/examples/Arduino_AT_Debug/utilities.h#L74

**Comment by pilot1981** [comment]
It seems to have hardware problem on SIM800 module: if I call SIM in SIM800, ISP say it is in reachable…


How I can check it?

**Comment by pilot1981** [comment]
How I can manage PIN and PUK is SIM?

To have all working fine I have to setup PIN to 0000?

**Comment by lewisxhe** [comment]
Whether there is a pin code depends on whether your SIM card has set a password

**Comment by pilot1981** [comment]
I have some chance to have it working in Italian GSM network?

**Comment by lewisxhe** [comment]
If the operator GSM you use does not stop, it can be used. You just need to ensure that a SIM card without pin lock is connected to the board, and then connect the GSM antenna. Use AT+CGREG? Get the current card registration status to know whether it can be supported and used

**Comment by pilot1981** [comment]
I’m using ESPHOME firmware

**Comment by pilot1981** [comment]
I have to ma rain always:
PIN 4 to OFF
PIN 5 to ON

?

**Comment by pilot1981** [comment]
I solved in this way:

PIN 4 always OFF
PIN 5 always ON
PIN 23 always ON
