### ISSUE TITLE
Arduino_GSM_OTA - Example code broken

### ISSUE THREAD

**Issue by samad909** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#23]
The example listed on the following URL is broken - https://github.com/Xinyuan-LilyGO/TTGO-T-Call/blob/master/examples/Arduino_GSM_OTA/Arduino_GSM_OTA.ino

Error - 'parseURL' was not declared in this scope

**Comment by vshymanskyy** [comment]
I think you have "utilities.h" missing in your sketch folder.

**Comment by samad909** [comment]
Damn! You are correct.
I was using the utilities.h from Arduino_TinyGSM example xD

//closing

**Comment by samad909** [comment]
Now I am getting the following error,
'DEBUG_FATAL' was not declared in this scope

**Comment by lewisxhe** [comment]
Issues have not been active for a long time and will be closed. If there is a problem, please reopen it.
