### ISSUE TITLE
SIM card damage after some time 

### ISSUE THREAD

**Issue by watcherkb** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#231]
I have a new Sim card. It worked well for a few minutes. After I have flashed different sketches with arduino, the Sim card stopped working. I have put the card to two different mobile phones but the card is not recognized anymore. Do I have to put the card off the board before flashing?

**Comment by lewisxhe** [comment]
It is not necessary to remove the SIM card. Even if the SIM card is uploaded on the board, the SIM card should not be damaged
