### ISSUE TITLE
utilities.h problem

### ISSUE THREAD

**Issue by rchl99** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#235]
I dont know it is me or anyone have the same problem, when I try the example code for Arduino_BlynkClient, [Arduino_MQTT], copy the code into the arduino ide, and it cannot compile the code and showing the error of #error "Please select the corresponding model", it would be apperciated if anyone is able to help my problem. Thank you.
![Screenshot 2023-05-07 215032](https://user-images.githubusercontent.com/56149816/236681648-d9e1cbe8-ad62-469f-8883-a75b8208fd4a.png)

**Comment by lewisxhe** [comment]
Select your board model above the sketch and cancel the annotation.

**Comment by rchl99** [comment]
okay thank you, can do it already
