### ISSUE TITLE
Cannot flash

### ISSUE THREAD

**Issue by Mesmer88** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#31]
When trying to flash with platformIO i'm getting this error:

Connecting........_____....._____....._____....._____....._____....._____....._____

A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header

On some other boards i would have kept BOOT button pressed but T-call doesn't have one.
Any hints?

**Comment by Mesmer88** [comment]
Update, seems to be working but very low success rate: like 2 in 10 attempts if i keep resetting board during flashing.

**Comment by lepetitcreole** [comment]
Hi, I have the same issue! Flashing rarely works on my board too, I need to try more 10 times before to make it work.

**Comment by slechta** [comment]
Same issue here. The first day everything was fine and second day I am getting:
```
A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header

**Comment by cfficaurzua** [comment]
After a lot of errors, i found out that the trick is to press reset 3 times between the last dot and the dashes. (with rhythm ♩♩♩)
e.g: 
**Connecting**........_____..... (click here 3 times) ____
Now the code always uploads.
why? ¯\_(ツ)_/¯
how to fix it? ¯\_(ツ)_/¯

**Comment by slechta** [comment]
When I disconnected the module from the daughterboard (self-made) the flashing started working. So either there was some kind of short-circuit or there was parasite capacitance on some pin.

**Comment by slechta** [comment]
Note: Threre is no need to push any button. The UART CTS/RTS signals are able to reset the board to download mode even if there is already sotware running.

**Comment by roberto1984** [comment]
Hi,

i have the same issue, i selected the ESP32 dev module board but it does not flash, i receive a timeout..which are the parameters to set on arduino after the ESP32 dev board has been selected?(i mean for instance flash mode,flash size, flash frequency and so on..)
Thank you in advance

**Comment by maromme** [comment]
pin 0 to ground puts the board in download mode. that's necessary at least if you program not using USB. bug well, give it a try

**Comment by roberto1984** [comment]
Thanks maromme!it did the trick!!!!

**Comment by maromme** [comment]
you're welcome.
for complete description:  it's necessary to to remove the connection of pin 0 to ground andpress the reset button after  download

**Comment by JB-DX** [comment]
I had the same problem. The reason is the very weird structure of RTS/DTR circuit.  IO0 jumps high exactly when EN goes high. So ESP32 never sees IO0=0 at start.
Delaying EN a bit solves that. A 1uF from EN to ground fixes it.

**Comment by vicival** [comment]
> **Delaying EN a bit solves that**.    A **1uF from EN to ground** fixes it.
  
  Thanks!

**Comment by jfchiantera** [comment]
if you connect io0 to GND and press reset you receive in serial port 

rst:0x1 (POWERON_RESET),boot:0x3 (DOWNLOAD_BOOT(UART0/UART1/SDIO_REI_REO_V2))
waiting for download

**Comment by mariusgrams** [comment]
Hi guys, I have the problem too, but I can't get it fixed. I connected GPIO 0 to GND, but nothing has changed. 

![connection](https://user-images.githubusercontent.com/39212237/87776964-ec7bba00-c828-11ea-8744-2a8b235a51e2.PNG)

I always get the error: Failed to connect to ESP32: Timed out waiting for packet header.
Could someone explain in more detail how they fixed the problem?

**Comment by jacoherotel** [comment]
> After a lot of errors, i found out that the trick is to press reset 3 times between the last dot and the dashes. (with rhythm ♩♩♩)
> e.g:
> **Connecting**........_____..... (click here 3 times) ____
> Now the code always uploads.
> why? ¯_(ツ)_/¯ how to fix it? ¯_(ツ)_/¯

works like a charm thnx

**Comment by reddy9698** [comment]
Hi guys I have almost the same problem. The module was working perfectly and suddenly the upload started failing at 0x00034864 address. I have tried all the methods and there's no difference.
`Compressed 230000 bytes to 121170...
Writing at 0x00010000... (12 %)
Writing at 0x0001f010... (25 %)
Writing at 0x00024f87... (37 %)
Writing at 0x0002c228... (50 %)
Writing at 0x00034864... (62 %)

A fatal error occurred: Timed out waiting for packet header
*** [upload] Error 2`
