### ISSUE TITLE
GPIO mistake ?

### ISSUE THREAD

**Issue by creatron** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#32]
In the pinout 'picture' we have 
15, GPIO15-ADC13-TOUCH3 then 
 2, GPIO2-ADC-12-TOUCH2
 0, GPIO0-ADC-11-TOUCH1
 **4, GPIO13-ADC10-TOUCH5** 
But also 
13, GPIO13-ADC14-TOUCH4
Two GPIO13?  should it not be
 **4, GPIO4-ADC10-TOUCH5**  ?

**Comment by Terxeno** [comment]
Yes! I checked the multimeter, the correct GPIO names are written on a gray background (Name)

**Comment by mide-X** [comment]
The Same thing for GPIO33 and GPIO32 which was also repeated twice

**Comment by lewisxhe** [comment]
Pin diagram has been updated
