### ISSUE TITLE
Any plans for a new board revision with SIM7000G or SIM7020G?

### ISSUE THREAD

**Issue by projecta98** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#38]
Are there any plans to release a new TTGO board with SIM7000G or SIM7020G module (for LTE support)?

Thanks.

**Comment by ClemensGruber** [comment]
Already out, see https://github.com/Xinyuan-LilyGO/LilyGO-T-SIM7000G and https://de.aliexpress.com/item/4000542688096.html but more expensive than the T-Call!

**Comment by lewisxhe** [comment]
Issues have not been active for a long time and will be closed. If there is a problem, please reopen it.
