### ISSUE TITLE
Modbus connect

### ISSUE THREAD

**Issue by edvkuhlmann** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#45]
I am a beginner in ESP32 programming and use the Arduino IDE. I would like to read data from a device via modbus. I have a RS 485 breakout to connect to the modbus device. As a Libary I thought smarmengol /Modbus master-slave for Arduino.
For this I need a serial interface. The first is occupied by the USB port. The 2nd with the SIM800. Is a 3rd possible? And how can I connect and address them? 
For help, I would be grateful.

**Comment by Krezalis** [comment]
is register for control data direction?

**Comment by edvkuhlmann** [comment]
I use GPIO 32 for switching and the device use 9600baud and even parity

**Comment by lewisxhe** [comment]
Can use softwareSerial and then external Modbus converter

**Comment by lewisxhe** [comment]
Issues have not been active for a long time and will be closed. If there is a problem, please reopen it.
