### ISSUE TITLE
How to connect external antenna on ESP32 module?

### ISSUE THREAD

**Issue by emigbur** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#53]
Hi
I saw that the EPS32 module has to solder contact, near the internal antenna, is possible to disable the internal ant and replaced for external?s
My idea is to put the boar into a box and connect an external antenna outside the box.
Thanks

**Comment by lewisxhe** [comment]
As shown in the figure, switch 1, to 2, but there is no IPX seat in the default module
![ANT](https://user-images.githubusercontent.com/22990954/86200896-8a685700-bb90-11ea-9cfc-09ba3c20fe58.jpg)

**Comment by ChrisKolan** [comment]
Could you explain how the switch should be made?
