### ISSUE TITLE
Rtc gpio on lilygo ttgo esp32 sim800l

### ISSUE THREAD

**Issue by Diedhert** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#54]
Does the lilygo esp32 sim800l has rtc gpio pins?
If yes, which ones? 

Regards
Diederik

**Comment by maromme** [comment]
hi, yes there are. check with the esp32 documentation which Pins to use. usually the ttgo pinout uses the same "names". but to be sure double check with the schematics of the ttgo.
I worked a lot with that tutorial https://randomnerdtutorials.com/esp32-external-wake-up-deep-sleep/

**Comment by lewisxhe** [comment]
Issues have not been active for a long time and will be closed. If there is a problem, please reopen it.
