### ISSUE TITLE
Board could not reset on power

### ISSUE THREAD

**Issue by dzungpv** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#56]
I have 4 boards, but 1 could not auto reset after power, must manual press the button or it will not work both the EPS and SIM800, i check the EN circuit but it is normal.
How to repair the unit?

**Comment by lewisxhe** [comment]
Have you solved this problem? If it has not been resolved, please let me know, otherwise please close this question

**Comment by dzungpv** [comment]
> Have you solved this problem? If it has not been resolved, please let me know, otherwise please close this question

It not solve, i have 4 but only this one. Try replace the resistor but not work

**Comment by lewisxhe** [comment]
Can't reset automatically on power-up. Generally, the automatic reset circuit is broken. Please check these two components.
![reset](https://user-images.githubusercontent.com/22990954/85246553-8300c980-b47d-11ea-9226-da1f49727f7e.jpg)
