### ISSUE TITLE
Kind of SIM card needed 

### ISSUE THREAD

**Issue by JMC1973** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#59]
I’ve a SIM card with a data plan and sms plan but without voice call plan. (Thingsmobile)
It’s impossible to get connection.
Is this kind of sim supported?
Thanks

**Comment by lewisxhe** [comment]
Support separate data, as long as it supports the frequency band

**Comment by Mr-HaleYa** [comment]
@JMC1973 
literally any sim card will work if it supports 2g and 3g. I use Twilio but hologram.io is nice as well

Please close if your issue is solved

**Comment by JMC1973** [comment]
Thank you, I have the board working. It’s mandatory use user and password to configure the apn.

**Comment by Mr-HaleYa** [comment]
not if your APN doesn't require it. As I said I use Twilio and all I have to do is pop it in and set the APN to them.
glad you resolved your issue
