### ISSUE TITLE
ESP_EXT1_WAKEUP_ANY_LOW

### ISSUE THREAD

**Issue by grichfitz** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#60]
Does anyone know how to complete a wake up from pin going low?

Just the way my project has gone. 

TIA

**Comment by lewisxhe** [comment]
see there 

https://github.com/espressif/arduino-esp32/blob/master/libraries/ESP32/examples/DeepSleep/ExternalWakeUp/ExternalWakeUp.ino

**Comment by grichfitz** [comment]
Not tried this example as found a work around, but will save this for the future.
thx
