### ISSUE TITLE
There are multiple errors in the pinOuts picture - GPIO13, GPIO32, GPIO33

### ISSUE THREAD

**Issue by vicival** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#64]
I'm talking about your  **TTGO-TCall-SIM800-ESP32-Pinout.jpg**   picture which is copied/posted
on a zillion websites that are selling this board. It's a flagship picture and **it should've been** flawless! 
![errors_TTGO-TCall-SIM800-ESP32-Pinout](https://user-images.githubusercontent.com/37894588/82380329-935df880-9a28-11ea-8fa8-1d037172490a.jpg)

**Comment by lewisxhe** [comment]
Sorry, I have notified to request changes.
