### ISSUE TITLE
How can I configure GPS tracker with TTGO-T-Call Module

### ISSUE THREAD

**Issue by smartkodian** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#67]
Hi Guys,

I hope all of you fine and stay safe!

I am wondering if there is an example explain how GPS track working with TTGO-T-Call ESP32 module, because all example I got it is related to GSM SMS. but didn't find any GPS example.

Any help please :)

Thanks for all

**Comment by lewisxhe** [comment]
SIM800L does not support GPS

**Comment by alexrmrm** [comment]
have that board some extra tx/rx for connect neo-gps?

**Comment by lewisxhe** [comment]
Issues have not been active for a long time and will be closed. If there is a problem, please reopen it.
