### ISSUE TITLE
redefinition error due to utilites.h in examples

### ISSUE THREAD

**Issue by crash007** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#7]
I cant compile the examples due to redfinition error in utilites.h
Suggested fix would be:
```
#ifndef UTILITIES_H_INCLUDED
#define UTILITIES_H_INCLUDED
...
#ENDIF
```

Error log:
`./utilities.h: In function 'bool setPowerBoostKeepOn(int)':
../utilities.h:6:6: error: redefinition of 'bool setPowerBoostKeepOn(int)'
 bool setPowerBoostKeepOn(int en)
      ^
In file included from ../sloeber.ino.cpp:25:0:
../utilities.h:6:6: note: 'bool setPowerBoostKeepOn(int)' previously defined here
 bool setPowerBoostKeepOn(int en)`

**Comment by vshymanskyy** [comment]
By the way, do you build with Arduino IDE or Platformio?

**Comment by crash007** [comment]
Im using Eclipse.

**Comment by emigbur** [comment]
Hi, I got this error
Arduino: 1.8.9 (Windows Store 1.8.21.0) (Windows 10), Board: "ESP32 Wrover Module, Default, QIO, 80MHz, 921600, None"

C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\hardware -hardware C:\Users\emigbur\Documents\ArduinoData\packages -hardware C:\Users\emigbur\Documents\Arduino\hardware -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\tools-builder -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\hardware\tools\avr -tools C:\Users\emigbur\Documents\ArduinoData\packages -built-in-libraries C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\libraries -libraries C:\Users\emigbur\Documents\Arduino\libraries -fqbn=esp32:esp32:esp32wrover:PartitionScheme=default,FlashMode=qio,FlashFreq=80,UploadSpeed=921600,DebugLevel=none -vid-pid=10C4_EA60 -ide-version=10809 -build-path C:\Users\emigbur\AppData\Local\Temp\arduino_build_650087 -warnings=default -build-cache C:\Users\emigbur\AppData\Local\Temp\arduino_cache_902053 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.esptool.path=C:\Users\emigbur\Documents\ArduinoData\packages\esp32\tools\esptool\2.3.1 -prefs=runtime.tools.esptool-2.3.1.path=C:\Users\emigbur\Documents\ArduinoData\packages\esp32\tools\esptool\2.3.1 -prefs=runtime.tools.mkspiffs.path=C:\Users\emigbur\Documents\ArduinoData\packages\esp32\tools\mkspiffs\0.2.3 -prefs=runtime.tools.mkspiffs-0.2.3.path=C:\Users\emigbur\Documents\ArduinoData\packages\esp32\tools\mkspiffs\0.2.3 -prefs=runtime.tools.xtensa-esp32-elf-gcc.path=C:\Users\emigbur\Documents\ArduinoData\packages\esp32\tools\xtensa-esp32-elf-gcc\1.22.0-80-g6c4433a-5.2.0 -prefs=runtime.tools.xtensa-esp32-elf-gcc-1.22.0-80-g6c4433a-5.2.0.path=C:\Users\emigbur\Documents\ArduinoData\packages\esp32\tools\xtensa-esp32-elf-gcc\1.22.0-80-g6c4433a-5.2.0 -verbose C:\Users\emigbur\Documents\Arduino\TTGO-T-Call_v1\TTGO-T-Call_v1.ino
C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\arduino-builder -compile -logger=machine -hardware C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\hardware -hardware C:\Users\emigbur\Documents\ArduinoData\packages -hardware C:\Users\emigbur\Documents\Arduino\hardware -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\tools-builder -tools C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\hardware\tools\avr -tools C:\Users\emigbur\Documents\ArduinoData\packages -built-in-libraries C:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.21.0_x86__mdqgnx93n4wtt\libraries -libraries C:\Users\emigbur\Documents\Arduino\libraries -fqbn=esp32:esp32:esp32wrover:PartitionScheme=default,FlashMode=qio,FlashFreq=80,UploadSpeed=921600,DebugLevel=none -vid-pid=10C4_EA60 -ide-version=10809 -build-path C:\Users\emigbur\AppData\Local\Temp\arduino_build_650087 -warnings=default -build-cache C:\Users\emigbur\AppData\Local\Temp\arduino_cache_902053 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.esptool.path=C:\Users\emigbur\Documents\ArduinoData\packages\esp32\tools\esptool\2.3.1 -prefs=runtime.tools.esptool-2.3.1.path=C:\Users\emigbur\Documents\ArduinoData\packages\esp32\tools\esptool\2.3.1 -prefs=runtime.tools.mkspiffs.path=C:\Users\emigbur\Documents\ArduinoData\packages\esp32\tools\mkspiffs\0.2.3 -prefs=runtime.tools.mkspiffs-0.2.3.path=C:\Users\emigbur\Documents\ArduinoData\packages\esp32\tools\mkspiffs\0.2.3 -prefs=runtime.tools.xtensa-esp32-elf-gcc.path=C:\Users\emigbur\Documents\ArduinoData\packages\esp32\tools\xtensa-esp32-elf-gcc\1.22.0-80-g6c4433a-5.2.0 -prefs=runtime.tools.xtensa-esp32-elf-gcc-1.22.0-80-g6c4433a-5.2.0.path=C:\Users\emigbur\Documents\ArduinoData\packages\esp32\tools\xtensa-esp32-elf-gcc\1.22.0-80-g6c4433a-5.2.0 -verbose C:\Users\emigbur\Documents\Arduino\TTGO-T-Call_v1\TTGO-T-Call_v1.ino
Using board 'esp32wrover' from platform in folder: C:\Users\emigbur\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.0
Using core 'esp32' from platform in folder: C:\Users\emigbur\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.0
Build options changed, rebuilding all
Detecting libraries used...
"C:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\tools\\xtensa-esp32-elf-gcc\\1.22.0-80-g6c4433a-5.2.0/bin/xtensa-esp32-elf-g++" -DESP_PLATFORM "-DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"" -DHAVE_CONFIG_H "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/config" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/bluedroid" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/bluedroid/api" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/app_trace" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/app_update" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/bootloader_support" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/bt" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/driver" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/esp32" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/esp_adc_cal" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/esp_http_client" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/esp-tls" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/ethernet" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/fatfs" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/freertos" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/heap" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/jsmn" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/log" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/mdns" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/mbedtls" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/mbedtls_port" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/newlib" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/nvs_flash" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/openssl" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/spi_flash" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/sdmmc" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/smartconfig_ack" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/spiffs" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/tcpip_adapter" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/ulp" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/vfs" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/wear_levelling" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/xtensa-debug-module" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/coap" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/console" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/expat" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/json" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/lwip" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/newlib" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/nghttp" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/soc" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/wpa_supplicant" -std=gnu++11 -fno-exceptions -Os -g3 -Wpointer-arith -fexceptions -fstack-protector -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib -w -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-sign-compare -fno-rtti -c -w -x c++ -E -CC -DF_CPU=240000000L -DARDUINO=10809 -DARDUINO_ESP32_DEV -DARDUINO_ARCH_ESP32 "-DARDUINO_BOARD=\"ESP32_DEV\"" "-DARDUINO_VARIANT=\"esp32\"" -DESP32 -DCORE_DEBUG_LEVEL=0 -DBOARD_HAS_PSRAM -mfix-esp32-psram-cache-issue "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0\\cores\\esp32" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0\\variants\\esp32" "C:\\Users\\emigbur\\AppData\\Local\\Temp\\arduino_build_650087\\sketch\\TTGO-T-Call_v1.ino.cpp" -o nul
"C:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\tools\\xtensa-esp32-elf-gcc\\1.22.0-80-g6c4433a-5.2.0/bin/xtensa-esp32-elf-g++" -DESP_PLATFORM "-DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"" -DHAVE_CONFIG_H "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/config" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/bluedroid" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/bluedroid/api" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/app_trace" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/app_update" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/bootloader_support" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/bt" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/driver" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/esp32" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/esp_adc_cal" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/esp_http_client" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/esp-tls" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/ethernet" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/fatfs" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/freertos" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/heap" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/jsmn" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/log" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/mdns" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/mbedtls" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/mbedtls_port" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/newlib" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/nvs_flash" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/openssl" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/spi_flash" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/sdmmc" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/smartconfig_ack" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/spiffs" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/tcpip_adapter" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/ulp" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/vfs" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/wear_levelling" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/xtensa-debug-module" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/coap" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/console" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/expat" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/json" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/lwip" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/newlib" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/nghttp" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/soc" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/wpa_supplicant" -std=gnu++11 -fno-exceptions -Os -g3 -Wpointer-arith -fexceptions -fstack-protector -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib -w -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-sign-compare -fno-rtti -c -w -x c++ -E -CC -DF_CPU=240000000L -DARDUINO=10809 -DARDUINO_ESP32_DEV -DARDUINO_ARCH_ESP32 "-DARDUINO_BOARD=\"ESP32_DEV\"" "-DARDUINO_VARIANT=\"esp32\"" -DESP32 -DCORE_DEBUG_LEVEL=0 -DBOARD_HAS_PSRAM -mfix-esp32-psram-cache-issue "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0\\cores\\esp32" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0\\variants\\esp32" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0\\libraries\\Wire\\src" "C:\\Users\\emigbur\\AppData\\Local\\Temp\\arduino_build_650087\\sketch\\TTGO-T-Call_v1.ino.cpp" -o nul
"C:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\tools\\xtensa-esp32-elf-gcc\\1.22.0-80-g6c4433a-5.2.0/bin/xtensa-esp32-elf-g++" -DESP_PLATFORM "-DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\"" -DHAVE_CONFIG_H "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/config" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/bluedroid" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/bluedroid/api" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/app_trace" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/app_update" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/bootloader_support" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/bt" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/driver" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/esp32" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/esp_adc_cal" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/esp_http_client" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/esp-tls" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/ethernet" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/fatfs" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/freertos" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/heap" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/jsmn" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/log" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/mdns" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/mbedtls" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/mbedtls_port" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/newlib" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/nvs_flash" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/openssl" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/spi_flash" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/sdmmc" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/smartconfig_ack" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/spiffs" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/tcpip_adapter" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/ulp" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/vfs" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/wear_levelling" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/xtensa-debug-module" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/coap" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/console" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/expat" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/json" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/lwip" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/newlib" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/nghttp" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/soc" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0/tools/sdk/include/wpa_supplicant" -std=gnu++11 -fno-exceptions -Os -g3 -Wpointer-arith -fexceptions -fstack-protector -ffunction-sections -fdata-sections -fstrict-volatile-bitfields -mlongcalls -nostdlib -w -Wno-error=unused-function -Wno-error=unused-but-set-variable -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wno-unused-parameter -Wno-sign-compare -fno-rtti -c -w -x c++ -E -CC -DF_CPU=240000000L -DARDUINO=10809 -DARDUINO_ESP32_DEV -DARDUINO_ARCH_ESP32 "-DARDUINO_BOARD=\"ESP32_DEV\"" "-DARDUINO_VARIANT=\"esp32\"" -DESP32 -DCORE_DEBUG_LEVEL=0 -DBOARD_HAS_PSRAM -mfix-esp32-psram-cache-issue "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0\\cores\\esp32" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0\\variants\\esp32" "-IC:\\Users\\emigbur\\Documents\\ArduinoData\\packages\\esp32\\hardware\\esp32\\1.0.0\\libraries\\Wire\\src" "-IC:\\Users\\emigbur\\Documents\\Arduino\\libraries\\TinyGSM\\src" "C:\\Users\\emigbur\\AppData\\Local\\Temp\\arduino_build_650087\\sketch\\TTGO-T-Call_v1.ino.cpp" -o nul
TTGO-T-Call_v1:41:23: error: utilities.h: No such file or directory

compilation terminated.

Using library Wire at version 1.0 in folder: C:\Users\emigbur\Documents\ArduinoData\packages\esp32\hardware\esp32\1.0.0\libraries\Wire 
Using library TinyGSM at version 0.7.9 in folder: C:\Users\emigbur\Documents\Arduino\libraries\TinyGSM 
exit status 1
utilities.h: No such file or directory

How can I install this file?

**Comment by lewisxhe** [comment]
Issues have not been active for a long time and will be closed. If there is a problem, please reopen it.
