### ISSUE TITLE
SD card Issue 

### ISSUE THREAD

**Issue by jenil163** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#74]
I Try to store data in SD CARD  WITH TTGo but hear all SPI uses some different connection like 23,5 are used for  SIM800L POWER AND RST SECOND SPI is For 13 for built-in led and third for FSPI so how can I connect and exchange data with SD card I see Issue #17  but not working with TTGO-T-CALL-SIM800L?
Anyone experience Please Help

**Comment by lewisxhe** [comment]
You can only use unused pins ，can you tell which pins you use?

**Comment by jenil163** [comment]
I use   clk=14, mosi=15, miso=2, cs=13 not working after connecting Mosi pin Module is every time reset

**Comment by jenil163** [comment]
![pinmap](https://user-images.githubusercontent.com/53688337/85398433-d9036900-b572-11ea-99ec-04e912b5fd72.JPG)

I use this device

**Comment by lewisxhe** [comment]
You used these pins, did you initialize it? As described here 

 #17

**Comment by jenil163** [comment]
I try But the same problem so initialization failed module works fine I check-in  Nodemcu I send you Code

**Comment by jenil163** [comment]
When I use  #17 pin  then this type of error I See
![Capture 2](https://user-images.githubusercontent.com/53688337/85504363-81640c80-b609-11ea-9d06-3973ead69314.JPG)
![pin sd card](https://user-images.githubusercontent.com/53688337/85504374-87f28400-b609-11ea-902f-a5f08965514c.JPG)




Configuring flash size...
Warning: Could not auto-detect Flash size (FlashID=0xffffff, SizeID=0xff), defaulting to 4MB
Compressed 8192 bytes to 47...

A fatal error occurred: Timed out waiting for packet content
An error occurred while uploading the sketch

**Comment by lewisxhe** [comment]
In T-Call, you can directly use SPI instead of HSPI, like this
```
    #include <SPI.h>
    #include <SD.h>
    SPI.begin(sck, miso, mosi);
    if (!SD.begin(sd_cs)) {
        // failed
    } else {
        //pass
    }
```
There is no error in your code, but did you upload it with the SD card inserted? GPIO12 is used as the flash voltage selection when ESP32 starts, please change a pin if you can

**Comment by jenil163** [comment]
First I try with inbuilt SPI pin no 23,5,18,19 but it's not working, TTGO support 8gb memory card?

**Comment by lewisxhe** [comment]
I am updating the warehouse and I will add an sd example.

**Comment by lewisxhe** [comment]
The code and instructions have been updated, I can use each version! Please check!

**Comment by natanel80** [comment]
@lewisxhe hi can you help me please i still not figure which pins i need to connect in order to work with sim800l and external sd together or if you have any code i will more than happy to see it

**Comment by jenil163** [comment]
@natanel80 which Device you use?  same or other

**Comment by lewisxhe** [comment]
@natanel80 I have uploaded the code, and the picture connected to the SD, have you checked it?

**Comment by natanel80** [comment]
@lewisxhe yes its all the time say "Card Mount Failed"

**Comment by lewisxhe** [comment]
You need to check your connection, do you apply the same SD card module as me? The SD card needs to be connected to 5V to work.

**Comment by natanel80** [comment]
this is the code right 
![2020-07-06_10-15-20](https://user-images.githubusercontent.com/35952968/86566078-afced980-bf71-11ea-9eba-d3f2a71cffe4.jpg)

**Comment by lewisxhe** [comment]
This is correct, I have verified it, and I have taken pictures and put them in the README.

**Comment by natanel80** [comment]
![WhatsApp Image 2020-07-06 at 10 17 00](https://user-images.githubusercontent.com/35952968/86566191-e60c5900-bf71-11ea-93f0-f9b63af91d86.jpeg)

**Comment by natanel80** [comment]
@lewisxhe the sd its ok?

**Comment by lewisxhe** [comment]
I’m right, please change the cable and try again. If it still doesn't work, please check the module for problems.

**Comment by natanel80** [comment]
@lewisxhe  ok thank you

**Comment by Cutiino** [comment]
Hello, I also am trying work with SD card and have a trouble with the 5V power. When I connect the SD card, the sim don't initialize but when I disconnect the SD, the sim initialize without problem.

**Comment by uvce12** [comment]
If you are using VSPI and the GPRS, pin 23 is used for powering up the SIM800L.

If you using HSPI, the pin 12 is always pulled high.

I was running my E-Ink on SPI and had no problems until I wrote the code for GPRS. Then, I redefined MOSI on VSPI to pin 21 instead of pin 23 and my SPI device works just fine.
