### ISSUE TITLE
can SIM/GPRS and the WiFi work simultaniously?

### ISSUE THREAD

**Issue by biswajitjei02** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#75]
is it possible to send receive data through sim/ and wifi simultaneously ? i mean receive data through sim/gprs and share via wifi mess?

**Comment by jenil163** [comment]
Both working but priority wise wifi is first priority if you use wifi and gsm both  you can create a different function for both for wifi and gsm at a time only one is working

**Comment by lewisxhe** [comment]
@jenil163 Already answered, if there is no problem please close the issue
