### ISSUE TITLE
FATAL: Timeout after 95%

### ISSUE THREAD

**Issue by fabioce** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#76]
33300 - Requesting /ota/ttgo-t-call-B.bin
34544 - Flashing...

 5%
 10%
 15%
 20%
 25%
 30%
 35%
 40%
 45%
 50%
 55%
 60%
 65%
 70%
 75%
 80%
 85%
 90%
 95%81598 - FATAL: Timeout

**Comment by jenil163** [comment]
understand the esp32 Partition then you understand why this error

**Comment by jenil163** [comment]
maybe your file is not written some specific time, that's why this happens because 2g gsm module

**Comment by lewisxhe** [comment]
Issues have not been active for a long time and will be closed. If there is a problem, please reopen it.
