### ISSUE TITLE
Led pin definition missing SIM800L_IP5306

### ISSUE THREAD

**Issue by muisje** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#78]
The definition of the led pin is missing. There seem to be two leds on the board. The one near the esp32 is a blue led on gpio13. This is currently marked with an X in the description instead of saying it's gpio13.

The other one is a red status led near and for the sim800L.

File:
https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/blob/master/doc/SIM800L_IP5306.MD

**Comment by lewisxhe** [comment]
Issues have not been active for a long time and will be closed. If there is a problem, please reopen it.
