### ISSUE TITLE
LilyGo-T-Call-SIM800L - How to detect power source USB-C or BATTERY

### ISSUE THREAD

**Issue by Vitaminazeta** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#79]
Hello everyone,
I'm looking to a way to detect if my LilyGo-T-Call-SIM800L is powered from USB-C connector or if running from battery.
My first option was to add an extra power supply (220VAC to 5V) connected only to a GPIO pin and detect if there is power. I wish to avoid this solution so save a second power suply unit on the project.
My second option was to connect the 5Vdc coming from USB-C to one of the GPIO pin. The problem here is how to get USB-C 5v. USB-C connector has a very small pins and I wan't be able to solder a wire without destroy the whole PCB.

Anyone knows if is possbile to detect power source on LilyGo-T-Call-SIM800L.
Actually I'm using Adafruits_FONA library where I should be able to measure battery capacity but not power source.
many thanks

**Comment by peteakalad** [comment]
If you have an AXP192 model some of the methods from the AXP library may help see:
https://github.com/lewisxhe/AXP202X_Library/blob/master/src/axp20x.h

**Comment by lewisxhe** [comment]
Issues have not been active for a long time and will be closed. If there is a problem, please reopen it.

**Comment by streem-ua** [comment]
Hey, @Vitaminazeta , have you solved your issue? I'm in such situation, like yours, trying to detect power source. 
Thanks!

**Comment by Vitaminazeta** [comment]
Hello!
I give up After months. If you find a way please be so kind to let me know

Giacomo

**Comment by streem-ua** [comment]
@Vitaminazeta Hey, go here! I managed how to know USB/VBAT
https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/issues/222

**Comment by lewisxhe** [comment]
see there https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/issues/222

**Comment by Vitaminazeta** [comment]
> see there #222

Many thanks lewisxhe
