### ISSUE TITLE
OTA status through Mqtt

### ISSUE THREAD

**Issue by jenil163** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#81]
@vshymanskyy  

Hi

I use  OTA-GSM, but I want also to use  Mqtt their so I can see the OTA status on remotely, But before calling The OTA function it's  working fine, then after I did not receive any message on remotely 

maybe the problem is here 

  Client* client = NULL;

how can I resolve it 

thankyou

**Comment by lewisxhe** [comment]
Issues will be closed if they have not been active for a long time. If there is a problem, please reopen it.
