### ISSUE TITLE
Add example to retrieve the network time

### ISSUE THREAD

**Issue by rgl** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#82]
It would be useful to have an example on how to get the network time. It seems it can de done with:

https://github.com/vshymanskyy/TinyGSM/blob/cddd356d0cca698ffcd324c0ca4702c1b92a2142/src/TinyGsmClientSIM800.h#L46

Can we have an example of that? I can even try to include it in https://github.com/Xinyuan-LilyGO/LilyGo-T-Call-SIM800/tree/master/examples/Arduino_TinyGSM if you would accept the PR and think its a good idea :-)

Showing a way to get the network time would be really useful, because the board does not have an RTC.

**Comment by peteakalad** [comment]
Did you look at the tinyGSM examples?

E.g. https://github.com/vshymanskyy/TinyGSM/blob/cddd356d0cca698ffcd324c0ca4702c1b92a2142/examples/AllFunctions/AllFunctions.ino#L404

**Comment by rgl** [comment]
I did, I thought this was a normal thing to do when we use this module that it would make sense to pull that example to this repository. But, I'm not sure anymore. So I'll close this. Sorry for the trouble.
