### ISSUE TITLE
Update code from server

### ISSUE THREAD

**Issue by grichfitz** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#83]
Hay helpful people,
Is there a way to update code remotely?
Eg... unit connects to server, checks code version and updates if required??
I have a feeling this not possible. 
TIA

**Comment by lewisxhe** [comment]
You can talk to the server first, get the latest version number, and then compare with your current version number. If the latest version, then get the latest firmware from the server, and then use ESP OTA to update.
