### ISSUE TITLE
Lipo battery with photovoltaic panel

### ISSUE THREAD

**Issue by gpalmia** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#84]
I would like to power the TTGO-TCALL with a lipo battery but I would also like to be able to recharge the battery with a photovoltaic panel.
The microcontroller sends data 24 out of 24 every hour to a remote database, therefore a charging phase cannot be alternated with a discharge phase.
Is it therefore possible to operate the microcontroller and simultaneously (especially during the day) to recharge the battery?

**Comment by lewisxhe** [comment]
There is a battery management chip on each board, if you need to use solar energy, you'd better use an additional solar battery management chip
