### ISSUE TITLE
Clarification on 5V pin

### ISSUE THREAD

**Issue by chendrix4** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#85]
**Is the 5V pin an input or output? If output, how much current can it source?**

In #36 , UCIS commented that "the 5V pin is connected to the output of the battery management IC" and "You can draw 5V from this pin for other components while the board is running (on battery or USB-C power)." In the schematic, however, the 5V pin seems like it's connected to the ACIN/VBUS0 trace, and the AXP192 datasheet lists VBUS as an input.

For further context, I intend to connect a 3.7V LiPo to the JST connector underneath the board.

**Comment by lewisxhe** [comment]
The appeal question refers to the IP5306 power supply version, not the AXP192 version, I will update the README, AXP192 version, 5V is only for input
