### ISSUE TITLE
IP5306 voltage instability issues wiht SIM800L_IP5306_VERSION_20190610

### ISSUE THREAD

**Issue by mbobinger** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#88]
Dear TTGO-fellows,

I'm having great fun with this product version:
SIM800L_IP5306_VERSION_20190610

My code works fine on it after implementing a few fixes:
1) 470uF cap soldered between GND and 5V for SIM800 current spikes
2) 2.0mm pitch JST plugs replaced by thicker cables for the LiPo battery
3) calling setupPMU in the setup to keep the battery charger powered, the exact function is explained in utilities.h

However: I'm still getting some instability issues after several transmissions and that seems really hard for me to troubleshoot now. I've observed that the module can hang in some zombie mode that consumes around 50mA, when the voltage drops below a critical value.

I've seen a similar issue opened in this thread. Is there by now some kind of a best practice how to use the TTGO module in battery powered mode?
What is the latest stable Hardware version that you recommend and could you please send me a link to that?

Thank you!

**Comment by lewisxhe** [comment]
SIM800L_IP5306_VERSION_20190610
It is an early version. MODEM does not support wake-up during sleep. I have feedback on the suggestions you have provided. At present, the more suitable version is AXP192, which supports MODEM to wake up ESP32.

https://pt.aliexpress.com/item/4000959701330.html
https://pt.aliexpress.com/item/4001274909689.html
