### ISSUE TITLE
Missing esp32.py lib

### ISSUE THREAD

**Issue by ebolisa** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#90]
Hi,
I'd like to read the internal board's temperature (tf = esp32.raw_temperature()) but I noticed that the esp32.py library is missing.
How do I get around it?
Thank you

**Comment by lewisxhe** [comment]
I remember that the internal temperature of esp32 has been disabled and cannot be read, please check the esp32 technical reference manual 

https://www.espressif.com/sites/default/files/documentation/esp32_technical_reference_manual_en.pdf
