### ISSUE TITLE
What is the difference between T-Call V1.3 and T-Call V1.4?

### ISSUE THREAD

**Issue by puffinpeter** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#96]
Hi, the link to the schematic of SIM800L IP5306 20200811 (I guess this is T-Call V 1.4) is broken. Could you @lewisxhe please clarify what's the difference between T-Call V1.3 and T-Call V1.4? Any chance to update the link. Thank you.

**Comment by lewisxhe** [comment]
They use the same power chip, but in V1.4, SIM800 leads to DTR and RI indications, which are used to wake up the sleeping modem and ringing indication.
