### ISSUE TITLE
Arduino_GSM_OTA example, backend documentation

### ISSUE THREAD

**Issue by samiul-hoque** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#98]
Is there any documentation on the backend part of the example code?  What is it actually doing in the backend? Just serving the bin file?

**Comment by lewisxhe** [comment]
The Arduino OTA code has been removed, and the binary file on the server does not match the existing board.
I don’t know the back end, so I can ask questions in TinyGSM
