### ISSUE TITLE
Problems with sending SMS

### ISSUE THREAD

**Issue by pertakman** [Xinyuan-LilyGO/LilyGo-T-Call-SIM800#99]
Hi!

My first attempt to get my T-Call going worked perfectly both via ESPHome as well using the example from https://RandomNerdTutorials.com/esp32-sim800l-send-text-messages-sms/

Without any obvious reason the module stopped sending SMS but I can still receive and get signal strength.
Any ideas of what could be wrong? Is my board defect?

Best regards,

Per Takman

**Comment by lewisxhe** [comment]
SMS already has a separate example. Please check it. Issues will be closed if they have not been active for a long time. If there is a problem, please reopen it.
